### ISSUE TITLE
Command-B hint may want to be more contrasty.

### ISSUE THREAD

**Issue by obra** [IvanMathy/Boop#26] opened 2020-06-16 18:10 UTC
It took me a few seconds to realize there was a hint about what to do in the UI. My eyes might be bad, but making the hint more visible could be nice.

<img width="668" alt="Screen Shot 2020-06-16 at 11 09 43 AM" src="https://user-images.githubusercontent.com/45416/84811557-e42e2600-afc1-11ea-8a56-9df6da0b5665.png">

**Comment by IvanMathy** [comment] 2020-06-16 18:13
Looks like a bug... Which version of macOS are you running?

**Comment by obra** [comment] 2020-06-16 18:31
Catalina 10.15.5 (19F101) 

<img width="698" alt="Screen Shot 2020-06-16 at 11 30 31 AM" src="https://user-images.githubusercontent.com/45416/84813412-cb733f80-afc4-11ea-9809-5b29f176a3eb.png">

**Comment by crankygeek** [comment] 2020-06-16 19:32
I see the same light text on MacBook Pro (15-inch, 2016) with macOS Mojave 10.14.6.

**Comment by fnky** [comment] 2020-06-16 20:14
Seems to be a problem with Boop not fully supporting light mode. While the status view itself uses system colors it seems that the rest of the UI uses hard-coded values.

This could maybe be fixed by setting the label's foreground color to `NSColor.labelColor` (or any other [system colors](https://developer.apple.com/documentation/appkit/nscolor/1534657-labelcolor)) which should be corrected when switching between light and dark mode.

Another fix is simply set the background color to a hard-coded value, similar to the rest of the UI.

**Comment by chockenberry** [comment] 2020-06-16 23:17
This caused by https://github.com/IvanMathy/Boop/issues/16 - the text being rendered there is using a named system color and Boop is not adapting its colors to light mode.

**Comment by IvanMathy** [comment] 2020-06-16 23:58
Yep, will be fixed with the light mode support update.

**Comment by IvanMathy** [comment] 2020-06-19 00:25
Fixed in #61

**Closed by IvanMathy** 2020-06-19 00:25 UTC
Labels: bug, good first issue
